config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    root 'homes#top'
    get '/customers/my_page' => 'customers#show', as: "show_customers"
    get '/customers/information/edit' => 'customers#edit', as: 'edit_customers'
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe_customers"
    patch '/customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers/withdraw', as: "withdraw_customers"

    resources :posts, only: [:new, :index, :show,:create]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  scope module: :admin do
    get "/admin/customers" => "customers#index", as: "customers_admin_index"
    get "/admin/customers/:id" => "customers#show", as: "customers_admin_show"
    get "/admin/customers/:id/edit" => "customers#edit", as: "customers_admin_edit"
    patch "/admin/customers/:id" => "customers#update", as: "customers_admin_update"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customers_admin_show_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :introduction, :email, :is_deleted)
  end

end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    customers_admin_index_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h2><%= @customer.name %>さんの会員情報編集</h2>

<%= form_with model: @customer, url: customers_admin_show_path do |f| %>

   <div class="form_group">
     <label for="customer_id">会員ID</label>
     <%= @customer.id %>
   </div>

   <div class="form_group">
     <label for="customer_name">氏名</label>
     <%= f.text_field :name %>
   </div>

  <div class="form_group">
     <label for="customer_email">メールアドレス</label>
     <%= f.text_field :email %>
  </div>


  <div class="is_deleted">
    <div>
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted, '退会', value: true %>
    </div>
    <div>
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, '有効', value: false %>
    </div>
  </div>

    <div class="form_group">
     <%= f.submit '変更を保存', class: "btn btn-success" %>
    </div>
<% end %>

app/views/admin/customers/index.html.erb
<h2>会員一覧</h2>

<table class="customers">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <% @customers.each do |customer| %>
    <tbody>
     <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.name, customers_admin_show_path(customer.id) %></td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_deleted %>
        退会
        <% else %>
        有効
        <% end %>
        </td>
     </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/customers/show.html.erb
<h2><%= @customer.name %>さんの会員詳細</h2>

<table class="customer.index">
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= @customer.name %></td>
  </tr>
    <td>メールアドレス</td>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <td>会員ステータス</td>
    <td>
      <% if @customer.is_deleted %>
        退会
        <% else %>
        有効
        <% end %>
    </td>
  </tr>
  <tr>
    <td></td>
    <td><%= link_to "編集する", customers_admin_edit_path, class: "btn btn-success" %></td>
    <td><%= link_to "投稿の一覧を見る",  customers_admin_edit_path, class: "glyphicon glyphicon-home btn btn-primary"  %></td>
  </tr>
</table>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c79c564768.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  </body>
  <header>
    <nav class="navbar navbar-expand-lg border-bottom">
    <div class="container">
    <%= link_to "ParkCommunity", root_path, class:"navbar-brand" %>
    <ul class="navbar-nav ml-auto">
    <% if admin_signed_in? %>
      <li>
        <%= link_to "投稿一覧", root_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to "会員一覧", customers_admin_index_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
      </li>
    <% elsif customer_signed_in? %>
    <p>ようこそ<%= current_customer.name %>さん!</p>
      <li>
        <%= link_to "マイページ", show_customers_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to "投稿一覧", root_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to "新規投稿", new_post_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "マイページ", new_customer_registration_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to "投稿一覧", new_customer_registration_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path,class:"navbar-brand" %>
      </li>
      <li>
        <%= link_to 'ログイン', new_customer_session_path %>
      </li>
      <% end %>
    </ul>
    </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>